name: Renovate

on:
  schedule:
    - cron: "0 0 * * *" # jalan tiap hari jam 00:00 UTC
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Renovate
        uses: renovatebot/github-action@v43.0.8
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
          configurationFile: ../.github/renovate.json
